ДЗ - Лекция 3 - Тултип
js-tasks-ru/htmlcss-20240913_ildarado12 pull request #15
Opened 2024-09-29 14:58 UTC by ildarado12

2024-09-29 14:58 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-29 15:12 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-09-29 15:58 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-09-29 16:50 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-04 18:43 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-04 20:32 UTC, GSemikozov requested changes

2024-10-04 20:32 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 100px;
марджины на уровне блока не задаем

2024-10-05 07:07 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-05 07:14 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-05 16:19 UTC, GSemikozov approved these changes

2024-10-05 16:19 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-10-05 16:19 UTC, GSemikozov approved these changes

2024-10-05 16:20 UTC, merged