ДЗ - Лекция 3 - Mодалка
js-tasks-ru/htmlcss-20240913_ildarado12 pull request #17
Opened 2024-10-07 20:17 UTC by ildarado12

2024-10-07 20:18 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-11 15:52 UTC, GSemikozov requested changes

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +            <div class="modal__shadow"></div>
лишний элемент, фон можно через rgba задавать сразу на уровне блока

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <h3 class="modal__window_title">Modal title</h3>
modal__title

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <svg id="modal-close" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
modal__close, и лучше завернуть в button

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <p class="modal__window_text">Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat s
modal__text

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +@import '/03-lection1/01-button/button.css';
ни в коем случае) наоборот - файлы стилей компонентов подключаем в main.css

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal {
а что если несколько модалок на странице? => .modal

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    display: none;
и все что указано в modal__shadow - сюда

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: relative;
а как выравниваем по серединке?

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__window_title {
см выше

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal-close {
.modal__close

2024-10-11 15:52 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__window_text {
см выше

2024-10-14 04:43 UTC, GSemikozov approved these changes

2024-10-14 04:43 UTC, merged