Dz lecture3 template
js-tasks-ru/htmlcss-20240913_ildarado12 pull request #18
Opened 2024-10-08 20:06 UTC by ildarado12

2024-10-08 20:11 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-11 16:04 UTC, GSemikozov requested changes

2024-10-11 16:04 UTC, GSemikozov commented on components/footer/index.css
> +    grid-area: footer;
блок ничего заранее не знает о контексте своего использования, а именно - что родитель обязательно грид с областями, где будет задействован данный блок. Корректнее - создать элементы у того родителя где мы это используем и замиксовать классы.

2024-10-11 16:04 UTC, GSemikozov commented on components/footer/index.css
> +    padding: 24px;
что-то лишнее

2024-10-11 16:04 UTC, GSemikozov commented on components/footer/index.css
> +.footer__heading_component {
.footer_component .footer__heading {}

2024-10-11 16:04 UTC, GSemikozov commented on components/header/index.css
> +    grid-area: header;
см выше

2024-10-11 16:04 UTC, GSemikozov commented on components/main/index.css
> +    padding: 36px 165px 68px;
по краям - лишнее (используем контейнер)

2024-10-11 16:04 UTC, GSemikozov commented on components/main/index.css
> +.main__grid_component {
`.main_component .main__grid`?

2024-10-13 12:49 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-13 13:52 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-14 04:47 UTC, GSemikozov requested changes

2024-10-14 04:47 UTC, GSemikozov commented on components/main/index.css
> +.main__grid_component {
не исправлено

2024-10-14 04:47 UTC, GSemikozov commented on components/page/index.css
> +.page_component .main {
.page_component .page__main

2024-10-14 04:47 UTC, GSemikozov commented on components/page/index.css
> +    padding: 36px 165px;
а зачем паддинги по краям?)

2024-10-14 04:47 UTC, GSemikozov commented on components/page/index.css
> +.page__componentMain {
здесь оставим только grid-area, остальное - как отдельный блок

2024-10-14 04:47 UTC, GSemikozov commented on components/page/index.css
> +    padding: 24px 165px;
удалим

2024-10-14 04:47 UTC, GSemikozov commented on components/page/index.css
> +.page__componentFooter .page__componentFooterHeading {
это просто еще один элемент футера

2024-10-27 12:22 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-12 08:03 UTC, GSemikozov approved these changes

2024-11-12 08:03 UTC, merged