ДЗ - Лекция 4 - Главная страница
js-tasks-ru/htmlcss-20240913_ildarado12 pull request #22
Opened 2024-10-13 16:17 UTC by ildarado12

2024-10-13 16:17 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-14 04:49 UTC, GSemikozov requested changes

2024-10-14 04:49 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    width: auto;
ой, почему здесь все поменяли? было правильно

2024-10-14 04:49 UTC, GSemikozov commented on components/card/index.css
> +.card .page__line {
через карту переопределяем внутреннюю реализацию другого блока? так нельзя, нужно стилизовать элемент карты

2024-10-14 04:49 UTC, GSemikozov commented on components/header/index.css
> +.header__logoSquare {
лого можно сделать одной свг картинкой

2024-10-14 15:45 UTC, ildarado12 commented on 06-lection4/01-avatar/avatar.css
> +    width: auto;
Тогда в карточке не расширяется до необходимого значения.

2024-10-14 19:06 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-18 08:16 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    width: auto;
надо использовать модификатор по типу avatar_large

2024-10-20 08:20 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-20 15:23 UTC, GSemikozov approved these changes

2024-10-20 15:23 UTC, merged