ДЗ - Лекция 5 - Радио
js-tasks-ru/htmlcss-20240913_ildarado12 pull request #25
Opened 2024-10-20 11:31 UTC by ildarado12

2024-10-20 11:32 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-20 15:26 UTC, GSemikozov requested changes

2024-10-20 15:26 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +                        <svg class="radio__icon" width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
отдельную иконку не надо, можно отрисовать через css

2024-10-20 16:53 UTC, GSemikozov requested changes

2024-10-20 16:53 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radioTitle {
удалить

2024-10-20 16:53 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    padding: 8px 0;
удалить

2024-10-20 16:53 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    display: flex;
inline-flex

2024-10-21 07:29 UTC, GSemikozov approved these changes

2024-10-21 07:29 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-10-21 07:30 UTC, GSemikozov approved these changes

2024-10-21 07:30 UTC, merged